/*
 - Rotina de criação das tabelas do banco de dados.

 Autor: Ronaldo Silveira
 Criado em: 19/11/2017
*/

Create table PROJETO(
ID INTEGER NOT NULL PRIMARY KEY,
DESCRICAO VARCHAR(50) NOT NULL,
DT_INICIO DATETIME NOT NULL,
DT_FIM DATETIME NOT NULL
);

Create table TAREFAS(
ID INTEGER NOT NULL PRIMARY KEY,
ID_PROJETO INTEGER NOT NULL,
DESCRICAO VARCHAR(50) NOT NULL,
DT_INICIO DATETIME NOT NULL,
DT_FIM DATETIME NOT NULL
);

Create table COLABORADOR(
ID INTEGER NOT NULL PRIMARY KEY,
NOME VARCHAR(50) NOT NULL,
EMAIL VARCHAR(50),
);

Create table TAREFA_COLABORADOR(
ID INTEGER NOT NULL PRIMARY KEY,
ID_COLABORADOR INTEGER NOT NULL,
ID_TAREFA INTEGER NOT NULL
);

Create table LISTA_TAREFAS(
ID INTEGER NOT NULL PRIMARY KEY,
ID_TAREFA INTEGER NOT NULL,
ID_TAREFA_PENDENTE INTEGER NOT NULL,
FINALIZADA VARCHAR(1) NOT NULL
);
